### ISSUE TITLE
Example for title slide

### ISSUE THREAD

**Issue by ronojoy** [szaghi/MaTiSSe#13]
@szaghi, very nice work with MaTiSSe!  Please could you provide an example for creating the title slide, say containing the presentation title, the authors name and affiliation, and maybe a logo, in a manner that resembles https://github.com/szaghi/MaTiSSe/blob/master/screenshots/01.png ? Thanks in advance.

**Comment by szaghi** [comment]
Hi @ronojoy ,

Thank you for interest. That title page is created with the following markdown:

```markdown
#titlepage[plain]

$box
$style[width:100%;height:35%;background:#4788B3;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[color:white;text-align:center;]{
$title[display:block;font-size:200%;padding-top:2%;]
$subtitle[display:block;font-size:120%;padding-top:2%;] 
$logo[height:50px;] 
}
$endbox

$box
$style[width:100%;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[text-align:center;]{
a presentation by $authors[display:block;font-size:150%]
$emails[display:block;font-size:90%;]
$affiliations[display:block;]
}
$endbox

$box
$style[width:100%;padding-top:2%;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[text-align:center;color:#4788B3;]{
$conference[display:block;font-size:150%;]
$session[display:block;font-size:120%;]
$location[display:block;font-size:90%;text-align:right;padding-right:5%;padding-top:5%;]
$date[display:block;font-size:90%;text-align:right;padding-right:5%;]
}
$endbox
```

Anyhow, you can find the source of the example here https://github.com/szaghi/MaTiSSe/blob/master/examples/getting-started/getting_started.md

The documentation for the titlepage is here https://github.com/szaghi/MaTiSSe/wiki/Titlepage

The full documentation is hosted into the wiki https://github.com/szaghi/MaTiSSe/wiki

I suggest to read the getting started example where almost all features are used and documented.

Thank you for trying matisse,

My best regards

**Comment by ronojoy** [comment]
@szaghi, thanks a lot.  While it was easy to get started with the main slides following your examples, it was not easy for me to figure out how to set up the title page (in spite of your nice title page example).  As a feature suggestion, can something like this  be incorporated directly into the themes ? Since the title variable is already included in the meta data, a macro equivalent to the Latex \maketitle could directly invoke all the code above and generate the title page, as defined by the theme. Thanks and best regards.

**Comment by szaghi** [comment]
Yes, it could be done. Today I can try to implement it as the default titlepage. Stay connect, see you soon.

**Comment by ronojoy** [comment]
Thanks!

**Comment by szaghi** [comment]
I am sorry, but today I found two serious bug (see the issues list) that have gained my attention. I hope to insert the *default* titlepage in the new version coming tomorrow.

I am sorry, but you must wait tomorrow.

**Comment by ronojoy** [comment]
No problem - I'll use your solution in the meantime.

**Comment by szaghi** [comment]
Ok, but pay attention to two bugs I found today: 

- https://github.com/szaghi/MaTiSSe/issues/16
- https://github.com/szaghi/MaTiSSe/issues/15

Until tomorrow, put all your slides into one md file for avoiding the include issue (themes definition is not affected by this bug, only slides content).

These bugs come from one of the refactoring I have recently done, I am sorry.

**Comment by szaghi** [comment]
Done.
