### ISSUE TITLE
Figure in columns environment

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#24]
I've a problem with multiple figure in columns environment: I want to put two figures side by side and to obtain this I create two columns of the same width (50%) and of the same height (50%); but when I insert the two figures and I try to specify the relative height of the two figures (100%), I obtain as output two big figures that fill a space that is bigger than the maximum column height.

Here a minimal working example:

---metadata
title              = Multi-Resolution Techniques for a Compressible Staggered LES Numerical Code
subtitle           =
authors            = ['Giacomo Rossi']
authors_short      = ['G. Rossi']
emails             = ['mail@uniroma1.it']
affiliations       = ['Dipartimento di Ingegneria Meccanica e Aerospaziale, Universita'' Sapienza']
affiliations_short = ['DIMA, Sapienza']
location           = Via Eudossiana 18, 00184 Roma
location_short     = Roma
date               = 29th February, 2015
conference         =
conference_short   =
session            =
session_short      =
logo               = images/Cherubino-Bianco-Trasparente.png
max_time           = 60
dirs_to_copy       = ['images']
---endmetadata

$include(sapienza_theme.md)

#titlepage[plain]

$box
$style[width:100%;height:35%;background:#822433;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[color:white;text-align:center;]{
$title[display:block;font-size:200%;padding-top:2%;]
$subtitle[display:block;font-size:120%;padding-top:2%;]
$logo[height:50px;]
}
$endbox

$box
$style[width:100%;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[text-align:center;]{
a presentation by $authors[display:block;font-size:150%]
$emails[display:block;font-size:90%;]
$affiliations[display:block;]
}
$endbox

$box
$style[width:100%;padding-top:2%;font-family:'Comic Sans MS', cursive, sans-serif;]
$content[text-align:center;color:#822433;]{
$conference[display:block;font-size:150%;]
$session[display:block;font-size:120%;]
$location[display:block;font-size:90%;text-align:right;padding-right:5%;padding-top:5%;]
$date[display:block;font-size:90%;text-align:right;padding-right:5%;]
}
$endbox

### Introduction

* Turbulent combustion is a phenomenon visible in a lot of common combusion systems, such as internal combustion engines, turbojets, liquid and solid rocket motors.

* Turbulent combustion is usually divided in premixed and non-premixed: in the first fuel and oxydizer are mixed before they reach the flame front, while in the second
the mixing is due to molecolar diffusion.

* Turbulent combustion is the result of a mutual interaction between chemical reactions and fluid structures: the turbulence is conditioned by the presence of the flame
front, because of the heat release and kinematic viscosity variations that speed up the fluid; the turbulence interacts with the flame structure, because strong mixing
can intensify chemical reactions or inhibit the combustion.

$columns

$column[width:50%;height:50%]

$figure
$content[height:100%]{images/prem_flame2.jpg}
$caption(None){Turbulent premixed flame}
$endfigure

$column[width:50%;height:50%]

$figure
$content[height:100%]{images/diff_flame2.jpg}
$caption(None){Turbulent diffusion flame}
$endfigure

$endcolumns

The sapienza_theme.md file contains the following text:

---theme_slide_global
data-offset     = 200
background      = white
border-radius   = 10px
---endtheme_slide_global

---theme_toc
font-variant = small-caps
---endtheme_toc

---theme_section_emph_toc
border        = 1px solid #822433
border-radius = 5px
---endtheme_section_emph_toc

---theme_subsection_emph_toc
border        = 1px solid #822433
border-radius = 5px
---endtheme_subsection_emph_toc

---theme_slide_emph_toc
border        = 1px solid #822433
border-radius = 5px
---endtheme_slide_emph_toc

---theme_slide_header_1
height        = 6%
padding       = 1% 2%
background    = #822433
color         = white
border-radius = 10px 10px 0 0
metadata      = [['slidetitle','float:left;font-variant:small-caps;font-size:150%;'],&&
                 ['logo','float:right;height:100%;']]
---endtheme_slide_header_1

---theme_slide_footer_1
height     = 3%
width      = 90%
float      = right
background = #822433
metadata   = []
---endtheme_slide_footer_1

---theme_slide_footer_2
height     = 6%
padding    = 1% 2%
background = #822433
color      = white
metadata   = [['title','padding:0 1%;'],                           &&
              ['date','padding:0 1%;'],                            &&
              ['total_slides_number','float:right;padding:0 1%;'], &&
              ['|custom| of ','float:right;'],                     &&
              ['slidenumber','float:right;padding:0 1%;'],         &&
              ['|custom|slide ','float:right;']]
---endtheme_slide_footer_2

---theme_slide_sidebar_1
active = False
---endtheme_slide_sidebar_1

---theme_figure
style   = font-variant:small-caps;text-align:center;
caption = font-size:80%;color:#822433;
---endtheme_figure

---theme_note
style   = display:inline-block;font-variant:small-caps;box-shadow: 7px 7px 5px rgba(200,200,200,0.3);border-radius:20px
caption = padding:0 2%;color:#822433;border-bottom:1px solid #822433;display:inline-block;
content = padding:0 2%;font-size:120%;
---endtheme_note

![mah](https://cloud.githubusercontent.com/assets/6975777/8163963/7277c318-1386-11e5-9683-f16b5038718b.jpeg)

**Comment by szaghi** [comment]
@giacombum 

Thank you for testing MaTiSSe.py.

This is probably a bug. The column environment should not *eat* all vertical spaces, but just as maximum as possible. Another cause could be inside the figure environment: maybe for the default css settings the dimensions of the figures are not relative to the div container (the columns in this case) rather they are absolute (and in this case the 100% height of the figure eat too much vertical space).

Tomorrow I will check the if problem is inside figure, columns or css.

See you tomorrow.

**Comment by giacombum** [comment]
Just for clarity: I'm using MaTiSSe.py 0.1.1 installed some days ago from pip.

**Comment by giacombum** [comment]
I think the problem is inside the figure environment: if I set two columns and in one I put a box and in the other a picture, and I set the picture width as 100%, the picture is too big; here's the minimun example:

$columns

$column[width:50%]

$box
$style[background:white;box-shadow:7px 7px 7px;border-radius:5px;]
$caption(none)[font-size:200%;font-variant:small-caps;color:#822433;position:TOP;]{Target}
$content[font-size:150%;color:black;]{Development of a mesh refinement algorithm for HeaRT ''in house'' numerical code, with staggered grids, for LES numerical simulations
on compressible reacting flows}
$endbox
&nbsp;

$box
$style[background:white;box-shadow:7px 7px 7px;border-radius:5px;]
$caption(none)[font-size:200%;font-variant:small-caps;color:#822433;position:TOP;]{Motivations}
$content(note)[font-size:150%;color:black;]{on compressible reacting flows}
$endbox

$column[width:50%]

$figure
$content[width=100%]{Figure/Red_zoom.jpg}
$caption(None){Turbulent diffusion flame}
$endfigure

$endcolumns

**Comment by szaghi** [comment]
Should be fixed in v1.0.0, please check.
