### ISSUE TITLE
Box caption position

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#25]
Is possible to introduce an option that defines the caption position in the box environment? In my opinion is useful in some cases that the caption operates as a title for the box.

**Comment by szaghi** [comment]
Sure it is possible.

ASAP it will implemented.

Thank you.

**Comment by szaghi** [comment]
Done in version 0.2.0 (both in PyPi and github).

Very soon I update the wiki [documentation](https://github.com/szaghi/MaTiSSe/wiki/Box-environment).

**Comment by szaghi** [comment]
Wiki page updated.
