### ISSUE TITLE
List in box environment

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#26]
I'm becoming a MaTiSSe addicted: this program is very very good, but unfortunately it lacks some useful LaTeX-Beamer features, like bullet lists in box environment. I hope that this feature can be easily added: thamk you @szaghi for your awesome work!

**Comment by szaghi** [comment]
Done. Fully markdown support has been added to both note and box environment. Now you can add not only bullet-items lists, but all markdown fancies. See the wiki.

This feature has been inhibited for figure and table...
