### ISSUE TITLE
Footnotes and citations

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#27]
I will not tire of repeating, once again, that MaTiSSe is a fantastic project; in order to obtain a complete tool for "Markdown To Impressive Scientific Slides", I think that an useful and indispensable feature could be the possibility to insert footnotes and a minimal bibliography with citations.

I don't know if could be of any help, but Pandoc and Multimarkdown markdown flavours support citations, using a bibtex file that contains citations.

Anyhow, thanks a lot @szaghi !

**Comment by szaghi** [comment]
@giacombum 

Sure citations are helpful. However, there is still not a *standard* way to handle citations in markdown, e.g. https://github.com/scholmd/scholmd/wiki/citations.

I will investigate, but this is not so simple.

**Comment by szaghi** [comment]
Footnote is currently well supported, see https://github.com/szaghi/MaTiSSe/blob/master/src/unittest/python/compare/footnotes/test.md

Citations have not a standard or common syntax/rule. Further study is necessary. I am closing this issue, and opening a new one tailored to citations.
