### ISSUE TITLE
LaTeX equations in boxes

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#28]
Is possible to add the opportunity of writing LaTeX equations in boxes? This feature could be very useful!

**Comment by szaghi** [comment]
It was already supported, but there was a small bug into the regex of the box(note, figure, table) contents capturing: it was set as non-greedy... this broken the latex equations that uses `{}` brackets (that are uses for delimiting box-like envs contents). Now the regex are greedy and the latex equations should be corrected rendered also into box and not envs (not into figure and table).

I am closing this issue, let me know if the fix does not work (in my unittest suite it does).

Thank you for testing MaTiSSe.py

**Comment by giacombum** [comment]
The issue is not completely solved: for some particular equations, like this

$$ p = \rho \sum \limits_{i=1}^{N_s} \frac{Y_i}{W_i} \mathcal{R}_u T $$

I still have some problems in compilig the formula with mathjax if the formula is inserted in a box.
