### ISSUE TITLE
Theme enhancement

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#29]
To obtain a maximum level of personalization (yes, often engineers are very cool and narcissist persons) could be very useful to modifiy the color of the bullets in a bullet-list or the color of the numbers in an arabic list: this can be obtained also with a simple change in the 'theme.css' produced by MaTiSSe, but I don't think that's the right way!

**Comment by szaghi** [comment]
It should be simple to implement into the main theme system.

I will try.

**Comment by szaghi** [comment]
Done in v1.1.1.

**Comment by szaghi** [comment]
See the getting started example, line 944.
