### ISSUE TITLE
Bullet list not available in box environment

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#30]
I suspect that with all the new features recently introduced, some bug rise up: using the last version is impossible to obtain a bullet list into the box environment.

Here a minimum work example:

---theme_slide_global border = 2px solid black ---endtheme_slide_global

# io

### ioioio

$box
$style[background:white;box-shadow:7px 7px 7px;border-radius:5px;max-width:95%]
$caption(none)[font-size:200%;position:TOP;]{Bullet list test}
$content[font-size:120%;color:black;]{
* test;
* test2.}
$endbox

**Comment by szaghi** [comment]
I am sorry, I know what happens... during the fix of larex equations issue I have *momentanely* disable the fix for bullets (for checking if it causes problem with equations) but I forget to reintroduce it!

Tomorrow I will reintroduce the fix purged out for a distraction... it was a busy day...

**Comment by szaghi** [comment]
In the new 0.3.3 (both PyPI/GItHub) should be fixed.
