### ISSUE TITLE
Round parenthesis

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#32]
I know that MaTiSSe uses Markdown, but in scientific presentations isn't infrequent the use of round parenthesis: is possible, in a tricky way (but you, @szaghi , are the master of complex tasks!), to introduce in MaTiSSe a character combination that can be used to obtain in the slides the round parenthesis?

**Comment by szaghi** [comment]
It should be a html/css default behavior. It should be configured by css. I will investigate.

**Comment by szaghi** [comment]
Found the **guilty**: it is MathJax that assume (due to my initialization) tha `( )` contains inline equations, thus the italic-no-white-spaces rendering. Fixed in the new v1.0.1.

P.S. now only `$` and `$$` tags are valid latex equations markers.
