### ISSUE TITLE
Table environment

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#33]
As I can see, the table environment relies on the "simple" Markdown syntax, that doesn't permit to obtain LaTeX like table environment (absence of vertical delimiters, absence of horizontal delimiters into the main part of the table, ecc...): I think that could be another very useful features to transform MaTiSSe in the perfect Beamer replacement if a new ambient (like figure, box, etc...) 'table' could be created.

**Comment by szaghi** [comment]
In the new v1.0.0 there is a theme for table.
