### ISSUE TITLE
Wrong figures-tables enumeration

### ISSUE THREAD

**Issue by giacombum** [szaghi/MaTiSSe#34]
The number of the "floating objects", as figures and tables, is unique: so, if I put ten figures and then a table, the table caption is 'Table 11', while it should be 'Table 1'; and if I add a figure after the table, the figure caption is 'Figure 12' while it should be 'Figure 11'.

**Comment by szaghi** [comment]
In the new version should not, but I will check later.

**Comment by szaghi** [comment]
Please, check if in the new version v1.0.0 the bug persists.

**Comment by szaghi** [comment]
There is no bug...
